import streamlit as st
import random

# --- PAGE SETUP ---
st.set_page_config(
    page_title="Navo Super Fast AI | Dhirendra Mishra",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- LIGHTNING FAST UI CSS ---
st.markdown("""
<style>
    .block-container {
        padding-top: 2rem !important;
        padding-bottom: 4rem !important;
        padding-left: 1rem !important;
        padding-right: 1rem !important;
    }
    .header-card {
        background: linear-gradient(135deg, #1e293b, #0f172a);
        border: 1px solid #38bdf8;
        border-radius: 10px;
        padding: 10px 14px;
        margin-bottom: 10px;
    }
    .title-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }
    .main-title {
        font-size: 1.1rem;
        font-weight: 800;
        color: #38bdf8;
        margin: 0;
    }
    .author-badge {
        background-color: #38bdf8;
        color: #0f172a;
        padding: 2px 8px;
        border-radius: 12px;
        font-size: 0.65rem;
        font-weight: 700;
    }
    .sub-title {
        font-size: 0.7rem;
        color: #94a3b8;
        margin-top: 2px;
        margin-bottom: 0;
    }
</style>
""", unsafe_allow_html=True)

# --- HEADER SECTION ---
st.markdown("""
<div class="header-card">
    <div class="title-row">
        <div class="main-title">⚡ Navo Ultra Super Fast AI</div>
        <div class="author-badge">By Dhirendra Mishra</div>
    </div>
    <div class="sub-title">Lightning Assistant with Smart Image Generation</div>
</div>
""", unsafe_allow_html=True)

# --- SIDEBAR CONTROLS ---
with st.sidebar:
    st.markdown("### ⚙️ Controls")
    st.success("🟢 **Status: Image Engine Active**")
    
    st.markdown("---")
    st.markdown("#### 📎 Attach File")
    uploaded_file = st.file_uploader(
        "Upload Image or PDF", 
        type=["png", "jpg", "jpeg", "pdf"]
    )
    if uploaded_file:
        st.success(f"Attached: {uploaded_file.name}")
        if uploaded_file.type.startswith("image/"):
            st.image(uploaded_file, caption="Preview", use_container_width=True)

    st.markdown("---")
    if st.button("🗑️ Clear Chat", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

# --- CHAT STATE ---
if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if "img_url" in msg and msg["img_url"]:
            st.image(msg["img_url"], caption="Generated by Navo AI", use_container_width=True)

# --- ADVANCED AI + IMAGE ENGINE ---
def get_ai_response(prompt):
    p = prompt.lower().strip()
    
    is_image_request = any(word in p for word in ["pic", "photo", "image", "bano", "banao", "draw", "generate", "design", "cake"])
    
    if is_image_request:
        if "cake" in p or "sweet" in p:
            img_url = "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80"
        elif "python" in p or "code" in p:
            img_url = "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80"
        else:
            img_url = "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80"
            
        reply_text = f"🎨 Aapki di gayi request (**'{prompt}'**) ke anusar yeh high-quality visual / image generate kar di gayi hai:"
        return reply_text, img_url
    
    elif "kaise ho" in p or "hello" in p or "hi" in p:
        return "Namaste! Main ekdam taiyar hoon. Batai, aaj kya design ya code banana hai?", None
    elif "python" in p or "code" in p:
        return "Yeh raha python code:\n```python\nprint('Navo AI Image & Code Engine Ready!')\n```", None
    else:
        return f"Aapka sawal mila: **'{prompt}'**\nNavo Ultra Fast engine ne is par behtareen response taiyar kar diya hai. Kuch aur update karna ho toh batayein!", None

# --- CHAT INPUT & HANDLER ---
if prompt := st.chat_input("Apna sawal yahan likhein ya pic banane ko kahein..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    reply_text, img_url = get_ai_response(prompt)

    msg_data = {"role": "assistant", "content": reply_text, "img_url": img_url}
    st.session_state.messages.append(msg_data)

    with st.chat_message("assistant"):
        st.markdown(reply_text)
        if img_url:
            st.image(img_url, caption="Generated by Navo AI", use_container_width=True)
