import streamlit as st
import urllib.parse

# --- PAGE SETUP ---
st.set_page_config(
    page_title="Navo Super Fast AI | Dhirendra Mishra",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- LIGHTNING FAST UI CSS ---
st.markdown("""
<style>
    .block-container {
        padding-top: 2rem !important;
        padding-bottom: 4rem !important;
        padding-left: 1rem !important;
        padding-right: 1rem !important;
    }
    .header-card {
        background: linear-gradient(135deg, #1e293b, #0f172a);
        border: 1px solid #38bdf8;
        border-radius: 10px;
        padding: 10px 14px;
        margin-bottom: 10px;
    }
    .title-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }
    .main-title {
        font-size: 1.1rem;
        font-weight: 800;
        color: #38bdf8;
        margin: 0;
    }
    .author-badge {
        background-color: #38bdf8;
        color: #0f172a;
        padding: 2px 8px;
        border-radius: 12px;
        font-size: 0.65rem;
        font-weight: 700;
    }
    .sub-title {
        font-size: 0.7rem;
        color: #94a3b8;
        margin-top: 2px;
        margin-bottom: 0;
    }
</style>
""", unsafe_allow_html=True)

# --- HEADER SECTION ---
st.markdown("""
<div class="header-card">
    <div class="title-row">
        <div class="main-title">⚡ Navo Ultra Super Fast AI</div>
        <div class="author-badge">By Dhirendra Mishra</div>
    </div>
    <div class="sub-title">Smart Gemini-Style Assistant (No Key Required)</div>
</div>
""", unsafe_allow_html=True)

# --- SIDEBAR CONTROLS ---
with st.sidebar:
    st.markdown("### ⚙️ Controls")
    st.success("🟢 **Status: Turbo Active (No Key Needed)**")
    
    st.markdown("---")
    st.markdown("#### 📎 Attach File / Image")
    uploaded_file = st.file_uploader(
        "Upload Image or PDF", 
        type=["png", "jpg", "jpeg", "pdf"]
    )
    if uploaded_file:
        st.success(f"Attached: {uploaded_file.name}")
        if uploaded_file.type.startswith("image/"):
            st.image(uploaded_file, caption="Preview", use_container_width=True)

    st.markdown("---")
    if st.button("🗑️ Clear Chat", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

# --- CHAT STATE ---
if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if "img_url" in msg and msg["img_url"]:
            st.image(msg["img_url"], caption=msg.get("img_caption", "Generated by Navo AI"), use_container_width=True)

# --- SMART GEMINI SIMULATION ENGINE ---
def get_navo_gemini_response(prompt):
    p = prompt.lower().strip()
    
    # 1. Image / Visual Request Detection
    is_image_request = any(word in p for word in ["pic", "photo", "image", "bano", "banao", "draw", "generate", "design", "dikhao", "ganesh", "shiv", "car", "lady"])
    
    if is_image_request:
        clean_query = p.replace("pic", "").replace("photo", "").replace("image", "").replace("bano", "").replace("banao", "").replace("dikhao", "").strip()
        if not clean_query:
            clean_query = p
        encoded_query = urllib.parse.quote(clean_query)
        img_url = f"https://source.unsplash.com/featured/600x400/?{encoded_query}"
        reply_text = f"🎨 Aapki di gayi talash ('{prompt}') ke anusaar yeh behtareen visual/image fetch kar di gayi hai:"
        return reply_text, img_url, clean_query.title()
    
    # 2. Identity / About Questions
    elif "kaun ho" in p or "tum kyon ho" in p or "who are you" in p:
        reply = "Main **Navo Ultra Super Fast AI** hoon, jise **Dhirendra Mishra** dwara design kiya gaya hai. Mera kaam aapki har tarah ki problem solve karna hai—chahe woh professional coding ho, bakery/confectionery management ho, ya instant image creation ho!"
        return reply, None, None

    # 3. Coding / Python Support
    elif "python" in p or "code" in p or "programming" in p:
        reply = """### 💻 Python Code & Development Support
Aapke sawal ke liye yeh raha ek behtareen aur clean code template:

```python
# Navo AI Lightning Script
def run_system():
    print("Navo AI Engine running at lightning speed!")

run_system()
