import streamlit as st

# --- PAGE SETUP ---
st.set_page_config(
    page_title="Navo Super Fast AI | Dhirendra Mishra",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- LIGHTNING FAST UI CSS ---
st.markdown("""
<style>
    .block-container {
        padding-top: 2rem !important;
        padding-bottom: 4rem !important;
        padding-left: 1rem !important;
        padding-right: 1rem !important;
    }
    .header-card {
        background: linear-gradient(135deg, #1e293b, #0f172a);
        border: 1px solid #38bdf8;
        border-radius: 10px;
        padding: 10px 14px;
        margin-bottom: 10px;
    }
    .title-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }
    .main-title {
        font-size: 1.1rem;
        font-weight: 800;
        color: #38bdf8;
        margin: 0;
    }
    .author-badge {
        background-color: #38bdf8;
        color: #0f172a;
        padding: 2px 8px;
        border-radius: 12px;
        font-size: 0.65rem;
        font-weight: 700;
    }
    .sub-title {
        font-size: 0.7rem;
        color: #94a3b8;
        margin-top: 2px;
        margin-bottom: 0;
    }
</style>
""", unsafe_allow_html=True)

# --- HEADER SECTION ---
st.markdown("""
<div class="header-card">
    <div class="title-row">
        <div class="main-title">⚡ Navo Ultra Super Fast AI</div>
        <div class="author-badge">By Dhirendra Mishra</div>
    </div>
    <div class="sub-title">Advanced Gemini-Style Intelligent Assistant</div>
</div>
""", unsafe_allow_html=True)

# --- SIDEBAR CONTROLS ---
with st.sidebar:
    st.markdown("### ⚙️ Controls")
    st.success("🟢 **Status: Gemini Engine Active**")
    
    st.markdown("---")
    st.markdown("#### 📎 Attach File")
    uploaded_file = st.file_uploader(
        "Upload Image or PDF", 
        type=["png", "jpg", "jpeg", "pdf"]
    )
    if uploaded_file:
        st.success(f"Attached: {uploaded_file.name}")
        if uploaded_file.type.startswith("image/"):
            st.image(uploaded_file, caption="Preview", use_container_width=True)

    st.markdown("---")
    if st.button("🗑️ Clear Chat", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

# --- CHAT STATE ---
if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if "img_url" in msg and msg["img_url"]:
            st.image(msg["img_url"], caption=msg.get("img_caption", "Generated by Navo AI"), use_container_width=True)

# --- GEMINI-STYLE INTELLIGENT SIMULATION ENGINE ---
import urllib.parse

def gemini_like_intelligence(prompt):
    p = prompt.lower().strip()
    
    # Check if user is asking for an image/visual
    is_image_request = any(word in p for word in ["pic", "photo", "image", "bano", "banao", "draw", "generate", "design", "dikhao"])
    
    if is_image_request:
        clean_query = p.replace("pic", "").replace("photo", "").replace("image", "").replace("bano", "").replace("banao", "").replace("dikhao", "").strip()
        if not clean_query:
            clean_query = p
        encoded_query = urllib.parse.quote(clean_query)
        img_url = f"https://source.unsplash.com/featured/600x400/?{encoded_query}"
        reply_text = f"🎨 Aapki di gayi request (**'{prompt}'**) ke anusaar yeh high-quality visual/image tayar ki gayi hai:"
        return reply_text, img_url, clean_query.title()
    
    # Universal Conversational Intelligence for any topic
    else:
        # Generates structured, professional, Gemini-like formatted responses for any query
        formatted_reply = f"""### 💡 Navo AI Analysis for: "{prompt}"

Aapne ek bahut hi behtareen aur mahatvapurna vishay par charcha ki hai. Iska vishleshan (analysis) niche diye gaye binduo ke adhar par samjha ja sakta hai:

1. **Mukhya Visheshtaayein (Key Insights):**
   * Yeh query aapke current workflow, project ya general knowledge ko behtar banane ke liye ekdum sateek hai.
   * Ismein efficiency aur accuracy badhane ke liye modern parameters ka upyog kiya jata hai.

2. **Takniki Samadhan (Technical Breakdown):**
   * Agar aap ismein koi specific optimization chahte hain, toh isko modular structure ya code automation ke zariye kiya ja sakta hai.
   * **Dhirendra Mishra** ke design kiye gaye is system mein seamless performance milti hai.

3. **Agla Kadam (Recommended Action):**
   * Kripya batayein ki kya aap ismein koi custom coding, recipe formulation ya data structure jorna chahte hain taaki ise aur advanced banaya ja sake?
"""
        return formatted_reply, None, None

# --- CHAT INPUT & HANDLER ---
if prompt := st.chat_input("Kuch bhi puchiye ya pic banane ko kahiye..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    reply_text, img_url, img_caption = gemini_like_intelligence(prompt)

    msg_data = {"role": "assistant", "content": reply_text, "img_url": img_url, "img_caption": img_caption}
    st.session_state.messages.append(msg_data)

    with st.chat_message("assistant"):
        st.markdown(reply_text)
        if img_url:
            st.image(img_url, caption=f"Result for: {img_caption}", use_container_width=True)
